### ISSUE TITLE
[ERROR] Swift.DecodingError.valueNotFound

### ISSUE THREAD

**Issue by indyfromoz** [Sherlouk/Odeon#3]
Environment - Latest code from `develop`, Xcode `10.1(10B61)`, iPhone XR running iOS `12.1`

```
[ERROR] objectMapping(Swift.DecodingError.valueNotFound(Swift.String, Swift.DecodingError.Context(codingPath: [CodingKeys<Array<OdeonFilmInCinema>>(stringValue: "data", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "film", intValue: nil), CodingKeys(stringValue: "genre", intValue: nil)], debugDescription: "Expected String value but found null instead.", underlyingError: nil)), Status Code: 200, Data Length: 10048)
[PRELOAD] Found 112 cinemas
[PRELOAD] Found the names of 25 film attributes
[PRELOAD] Found the names of 16 performance attributes
```

![image](https://user-images.githubusercontent.com/315443/51437013-bcaf2d00-1ceb-11e9-89a3-47fc763696f7.png)

I have added `MOVIEDB_API_KEY` as in `Info.plist`. The issue is in one of the API responses not returning the `genre`, possibly the Odeon API.

**Comment by Sherlouk** [comment]
Very much one of the downsides of using live data that you don't control or have a known schema for. It might work for a day, a week, a month but then one piece of content comes through in a way you didn't expect and 💥 nope it doesn't work!

I've made genre optional and pushed this up. Back up and running again for me!

**Comment by indyfromoz** [comment]
@Sherlouk Thank you for the fix and many thanks for sharing the code and the article. I was about to open a PR for the fix but was poking around the code. I am not sure if you pushed up the fix yet, I do not see any commit with the fix 🤔

**Comment by Sherlouk** [comment]
Heh 😅 Got caught in one of my pre-push hooks. Fixed, there now 😄 Thanks!
